### ISSUE TITLE
Variable coding and missing data

### ISSUE THREAD

**Issue by martinamorris** [vicenews/shot-by-cops#2]
Hi Allison,

Just verifying that an entry of "NA" means the data are missing.  In the race field, it could also have meant Native American, but I'm assuming that is coincidence.

Do you have a variable coding document up on the site?  If not, it would be helpful!

thx,
Martina

**Comment by rkarthur** [comment]
Hey Martina,

"NA" means the data was missing or ambiguous; it does not stand for Native American. We didn't actively break out Native Americans as a separate race group, which means that they were sometimes assigned to "other." It's also possible that if departments input "NA" in the subject race field, we read it in as missing. Because of this, if you are interested in calculating the proportion of Native Americans in our data, I would recommend searching through the raw department files.

We are working on a variable coding document.
-Rob

**Comment by martinamorris** [comment]
Thanks!

**Comment by atmccann** [comment]
@martinamorris variable coding is now in the README too!

**Comment by martinamorris** [comment]
> @martinamorris variable coding is now in the README too!

great! thx for letting me know Allison :)

we're also working on developing a GitHub repo of fatal police shootings, 
merging info from all of the different datasets out there and providing 
some basic code as you did for cleaning and per capita estimation.

i suspect the risks for Native Americans are as high or higher than for 
Blacks.  so i'll look into your raw datasets to see whether that info is 
worth trying to pull out.  i know that for the fatal shooting databases 
there's alot of missing data on race.  i'm hoping to try to crowdsource 
that moving forward.

best,
mm
